### ISSUE TITLE
"results" doesn't get added to the file's metadata

### ISSUE THREAD

**Issue by erwan** [mbanting/metalsmith-prismic#18]
Hi,

I'm trying the plugin but I can't get the content from to the template. I've added some logs and it appears that the content is correctly fetched, but it doesn't get added to the file metadata. When I inspect it, I only get the variables I've put but "results" is not present.

Any idea what's going on? Maybe you have a working example somewhere with the source available?

The code is here:

https://github.com/erwan/lemmonjp/blob/metalsmith/src/index.md

https://github.com/erwan/lemmonjp/blob/metalsmith/src/index.md

**Comment by hivearts** [comment]
Try to remove .cdn from your api url.

```
"metalsmith-prismic": {
      "url": "https://lemmonjp.cdn.prismic.io/api"
    }

```

**Comment by erwan** [comment]
It doesn't change anything.

**Comment by erwan** [comment]
Apparently it was because I put prismic-plugin after the template plugin in metalsmith.json, and the order matters.

**Comment by mbanting** [comment]
Hi @erwan sorry I didn't respond earlier. Long wknd here in Canada and I unplugged for a little bit. Glad you figured it out.
