### ISSUE TITLE
Rendering Prismic previews

### ISSUE THREAD

**Issue by aeirola** [mbanting/metalsmith-prismic#24]
Im using the plugin to build static websites from Prismic.io, and would very much like to be able to render previews of my as well. Unfortunately the current API of this plugin doesn't support passing the raw reference in the configuration, only the release name. In order to render the previews one would need to be able to specify the reference, as documented in https://developers.prismic.io/documentation/developers-manual#prismic-toolbar.

I'll make a pull-request with a suggested fix.

**Comment by mbanting** [comment]
Thank you!
